version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: interactive_curriculum_db
    environment:
      POSTGRES_DB: interactive_curriculum
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./Database/schema:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql

  backend:
    build: ./Backend/java-backend/auth
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/interactive_curriculum
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
