version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: interactive_curriculum_db
    environment:
      POSTGRES_DB: interactive_curriculum
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./Database/schema:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql

  java-backend:
    # build: ./Backend/java-backend/auth
    image: josorioam404/isc-java-backend:latest  # Changed from build
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/interactive_curriculum
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      PYTHON_API_URL: http://python-backend:8000
      FRONTEND_URL: http://54.89.37.108:5173
    depends_on:
      - db

  python-backend:
    # build: ./Backend/python-backend
    image: josorioam404/isc-python-backend:latest  # Changed from build
    container_name: python_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: interactive_curriculum
      DB_USER: admin
      DB_PASSWORD: admin123
      FRONTEND_URL: http://54.89.37.108:5173
    depends_on:
      - db

  frontend:
    # build: ./Frontend
    image: josorioam404/isc-frontend:latest  # Changed from build
    ports:
      - "5173:80"
    depends_on:
      - java-backend

volumes:
  postgres_data:
