"""
jwt_utils.py
Updated to decode JWT tokens generated by Java Spring Boot
Java stores the secret as HEX string, we need to convert it to bytes
"""

import jwt
import os
from datetime import datetime

# This MUST match your Java application.yml jwt.secret (as HEX string)
# From your Java: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
JWT_SECRET_HEX = os.getenv(
    "JWT_SECRET",
    "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
)

# Convert HEX string to bytes (same way Java does it)
JWT_SECRET = bytes.fromhex(JWT_SECRET_HEX)

# Java uses HS256 algorithm
JWT_ALGORITHM = "HS256"

def decode_jwt(token: str) -> dict:
    """
    Decode JWT token generated by Java Spring Boot.
    
    Args:
        token: JWT token string (without 'Bearer ' prefix)
        
    Returns:
        dict: Decoded token payload with userId, role, etc.
        
    Raises:
        jwt.ExpiredSignatureError: If token is expired
        jwt.InvalidTokenError: If token is invalid
    """
    try:
        # Remove quotes if present (from browser console copy)
        token = token.strip('"').strip("'")
        
        # Decode token using the byte secret (same as Java)
        decoded = jwt.decode(
            token,
            JWT_SECRET,
            algorithms=[JWT_ALGORITHM]
        )
        
        print(f"JWT decoded successfully: userId={decoded.get('userId')}, role={decoded.get('role')}")
        
        return decoded
        
    except jwt.ExpiredSignatureError:
        print("JWT token has expired")
        raise
    except jwt.InvalidTokenError as e:
        print(f"Invalid JWT token: {str(e)}")
        raise
    except Exception as e:
        print(f"Error decoding JWT: {str(e)}")
        raise


def validate_token(token: str) -> bool:
    """
    Validate if a JWT token is valid.
    
    Args:
        token: JWT token string
        
    Returns:
        bool: True if valid, False otherwise
    """
    try:
        decode_jwt(token)
        return True
    except:
        return False


def extract_user_id(token: str) -> int:
    """
    Extract user ID from JWT token.
    
    Args:
        token: JWT token string
        
    Returns:
        int: User ID
        
    Raises:
        ValueError: If userId not in token
    """
    decoded = decode_jwt(token)
    
    user_id = decoded.get("userId")
    if not user_id:
        raise ValueError("userId not found in token")
    
    return int(user_id)


def extract_user_role(token: str) -> str:
    """
    Extract user role from JWT token.
    
    Args:
        token: JWT token string
        
    Returns:
        str: User role (admin, student, etc.)
    """
    decoded = decode_jwt(token)
    return decoded.get("role", "unknown")
