version: "3.9"

services:
  db:
    image: postgres:15
    container_name: interactive_curriculum_db
    env_file:
      - ./env/database.env
    volumes:
      - ./Database/schema:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - isc-net

  java-backend:
    image: josorioam404/isc-java-backend:${IMAGE_TAG}
    networks:
      - isc-net
    depends_on:
      - db
    env_file:
      - ./env/java-backend.env

  python-backend:
    image: josorioam404/isc-python-backend:${IMAGE_TAG}
    container_name: python_backend
    networks:
      - isc-net
    depends_on:
      - db
    env_file:
      - ./env/python-backend.env

  frontend:
    image: josorioam404/isc-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
    networks:
      - isc-net
    depends_on:
      - java-backend
      - python-backend

networks:
  isc-net:
    driver: bridge

volumes:
  postgres_data:
