version: "3.9"

services:
  db:
    image: postgres:15
    container_name: interactive_curriculum_db
    env_file:
      - ../env.dev/database.env
    ports:
      - "5432:5432"
    volumes:
      - ../Database/schema:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - isc-net

networks:
  isc-net:
    driver: bridge

volumes:
  postgres_data:
